# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labmonitor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labmonitor.proto',
  package='labmonitor',
  syntax='proto2',
  serialized_options=_b('\n\023br.ufc.great.protocB\020LabMonitorProtos'),
  serialized_pb=_b('\n\x10labmonitor.proto\x12\nlabmonitor\"%\n\x06Sensor\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"E\n\x0bSensorsData\x12 \n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x12.labmonitor.Sensor\x12\x14\n\x0clast_updated\x18\x02 \x02(\t\"$\n\x03Led\x12\r\n\x05\x63olor\x18\x01 \x02(\t\x12\x0e\n\x06status\x18\x02 \x02(\t\"G\n\x06\x42uzzer\x12\x0c\n\x04\x66req\x18\x01 \x02(\x05\x12\x10\n\x08\x64uration\x18\x02 \x02(\x05\x12\r\n\x05times\x18\x03 \x02(\x05\x12\x0e\n\x06status\x18\x04 \x02(\t\"M\n\tActuators\x12\x1c\n\x03led\x18\x01 \x01(\x0b\x32\x0f.labmonitor.Led\x12\"\n\x06\x62uzzer\x18\x02 \x01(\x0b\x32\x12.labmonitor.Buzzer\"\xc0\x01\n\rClientRequest\x12<\n\x07reqType\x18\x01 \x02(\x0e\x32+.labmonitor.ClientRequest.ClientRequestType\x12-\n\x0e\x61\x63tuatorsValue\x18\x02 \x01(\x0b\x32\x15.labmonitor.Actuators\"B\n\x11\x43lientRequestType\x12\x14\n\x10GET_SENSORS_DATA\x10\x00\x12\x17\n\x13SET_ACTUATORS_VALUE\x10\x01\"\xb4\x02\n\x0eServerResponse\x12?\n\x08respType\x18\x01 \x02(\x0e\x32-.labmonitor.ServerResponse.ServerResponseType\x12\x43\n\nrespStatus\x18\x02 \x02(\x0e\x32/.labmonitor.ServerResponse.ServerResponseStatus\x12,\n\x0bsensorsData\x18\x03 \x01(\x0b\x32\x17.labmonitor.SensorsData\"C\n\x12ServerResponseType\x12\x14\n\x10GET_SENSORS_DATA\x10\x00\x12\x17\n\x13SET_ACTUATORS_VALUE\x10\x01\")\n\x14ServerResponseStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42\'\n\x13\x62r.ufc.great.protocB\x10LabMonitorProtos')
)



_CLIENTREQUEST_CLIENTREQUESTTYPE = _descriptor.EnumDescriptor(
  name='ClientRequestType',
  full_name='labmonitor.ClientRequest.ClientRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_SENSORS_DATA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ACTUATORS_VALUE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=459,
  serialized_end=525,
)
_sym_db.RegisterEnumDescriptor(_CLIENTREQUEST_CLIENTREQUESTTYPE)

_SERVERRESPONSE_SERVERRESPONSETYPE = _descriptor.EnumDescriptor(
  name='ServerResponseType',
  full_name='labmonitor.ServerResponse.ServerResponseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_SENSORS_DATA', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ACTUATORS_VALUE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=726,
  serialized_end=793,
)
_sym_db.RegisterEnumDescriptor(_SERVERRESPONSE_SERVERRESPONSETYPE)

_SERVERRESPONSE_SERVERRESPONSESTATUS = _descriptor.EnumDescriptor(
  name='ServerResponseStatus',
  full_name='labmonitor.ServerResponse.ServerResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=795,
  serialized_end=836,
)
_sym_db.RegisterEnumDescriptor(_SERVERRESPONSE_SERVERRESPONSESTATUS)


_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='labmonitor.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='labmonitor.Sensor.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='labmonitor.Sensor.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=69,
)


_SENSORSDATA = _descriptor.Descriptor(
  name='SensorsData',
  full_name='labmonitor.SensorsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='labmonitor.SensorsData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='labmonitor.SensorsData.last_updated', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=140,
)


_LED = _descriptor.Descriptor(
  name='Led',
  full_name='labmonitor.Led',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='labmonitor.Led.color', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='labmonitor.Led.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=178,
)


_BUZZER = _descriptor.Descriptor(
  name='Buzzer',
  full_name='labmonitor.Buzzer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='freq', full_name='labmonitor.Buzzer.freq', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='labmonitor.Buzzer.duration', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='times', full_name='labmonitor.Buzzer.times', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='labmonitor.Buzzer.status', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=251,
)


_ACTUATORS = _descriptor.Descriptor(
  name='Actuators',
  full_name='labmonitor.Actuators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='led', full_name='labmonitor.Actuators.led', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buzzer', full_name='labmonitor.Actuators.buzzer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=330,
)


_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='labmonitor.ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reqType', full_name='labmonitor.ClientRequest.reqType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actuatorsValue', full_name='labmonitor.ClientRequest.actuatorsValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CLIENTREQUEST_CLIENTREQUESTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=525,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='labmonitor.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='respType', full_name='labmonitor.ServerResponse.respType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='respStatus', full_name='labmonitor.ServerResponse.respStatus', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensorsData', full_name='labmonitor.ServerResponse.sensorsData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERRESPONSE_SERVERRESPONSETYPE,
    _SERVERRESPONSE_SERVERRESPONSESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=836,
)

_SENSORSDATA.fields_by_name['data'].message_type = _SENSOR
_ACTUATORS.fields_by_name['led'].message_type = _LED
_ACTUATORS.fields_by_name['buzzer'].message_type = _BUZZER
_CLIENTREQUEST.fields_by_name['reqType'].enum_type = _CLIENTREQUEST_CLIENTREQUESTTYPE
_CLIENTREQUEST.fields_by_name['actuatorsValue'].message_type = _ACTUATORS
_CLIENTREQUEST_CLIENTREQUESTTYPE.containing_type = _CLIENTREQUEST
_SERVERRESPONSE.fields_by_name['respType'].enum_type = _SERVERRESPONSE_SERVERRESPONSETYPE
_SERVERRESPONSE.fields_by_name['respStatus'].enum_type = _SERVERRESPONSE_SERVERRESPONSESTATUS
_SERVERRESPONSE.fields_by_name['sensorsData'].message_type = _SENSORSDATA
_SERVERRESPONSE_SERVERRESPONSETYPE.containing_type = _SERVERRESPONSE
_SERVERRESPONSE_SERVERRESPONSESTATUS.containing_type = _SERVERRESPONSE
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
DESCRIPTOR.message_types_by_name['SensorsData'] = _SENSORSDATA
DESCRIPTOR.message_types_by_name['Led'] = _LED
DESCRIPTOR.message_types_by_name['Buzzer'] = _BUZZER
DESCRIPTOR.message_types_by_name['Actuators'] = _ACTUATORS
DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), {
  'DESCRIPTOR' : _SENSOR,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.Sensor)
  })
_sym_db.RegisterMessage(Sensor)

SensorsData = _reflection.GeneratedProtocolMessageType('SensorsData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORSDATA,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.SensorsData)
  })
_sym_db.RegisterMessage(SensorsData)

Led = _reflection.GeneratedProtocolMessageType('Led', (_message.Message,), {
  'DESCRIPTOR' : _LED,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.Led)
  })
_sym_db.RegisterMessage(Led)

Buzzer = _reflection.GeneratedProtocolMessageType('Buzzer', (_message.Message,), {
  'DESCRIPTOR' : _BUZZER,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.Buzzer)
  })
_sym_db.RegisterMessage(Buzzer)

Actuators = _reflection.GeneratedProtocolMessageType('Actuators', (_message.Message,), {
  'DESCRIPTOR' : _ACTUATORS,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.Actuators)
  })
_sym_db.RegisterMessage(Actuators)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.ClientRequest)
  })
_sym_db.RegisterMessage(ClientRequest)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'labmonitor_pb2'
  # @@protoc_insertion_point(class_scope:labmonitor.ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
